### ISSUE TITLE
Moderncv underfull bad box without quote

### ISSUE THREAD

**Issue by Thrashophil** [moderncv/moderncv#121] opened 2022-05-07 09:03 UTC
The following minimal example gives an underfull bad box. When I uncomment the quote line, it somehow works. What is the problem? I don't understand the behavior. Is it possible to not use a quote and have no bad box at the same time?

```
\documentclass{moderncv}
\moderncvstyle{classic}
\usepackage{lmodern}
\name{John}{Smith}
%\quote{}  % uncomment to get rid of the underfull bad box

\begin{document}
    \makecvtitle
    \section{Education}
\end{document}
```

**Comment by stephanlachnit** [comment] 2022-05-07 14:33
Interesting that you found that a quote solves this, but seems like a duplicate of #108.

**Closed by stephanlachnit** 2022-05-07 14:33 UTC
Labels: bug
