### ISSUE TITLE
\moderncvcolor not respected in 2.4.1

### ISSUE THREAD

**Issue by smithjh-lafayette** [moderncv/moderncv#203] opened 2024-07-30 17:57 UTC
In version 2.4.1, the option \moderncvcolor is not followed.  No matter what color is provided, the section and subsection titles are black.  Using pdfLaTeX on a Mac via TeXShop.

Here is a minimum working example:

```
\documentclass[letterpaper, sans, 10pt]{moderncv}
\moderncvstyle{classic}
\moderncvcolor{red}

\name{First}{Last}

\begin{document}

\makecvtitle
\section{Education}

\end{document}
```

**Comment by smithjh-lafayette** [comment] 2024-07-30 18:00
I reviewed another submitted [issue](https://github.com/moderncv/moderncv/issues/198) that had been closed, and I see that \moderncvcolor needs to be before \moderncvstyle.  This is a change from previous behavior.

**Comment by LLdaniel** [comment] 2024-07-30 20:11
Hi @smithjh-lafayette ,
thanks for your own research! Yes, unfortunately we had to introduce a breaking change for color adjustments.

I will mark this as (kind of) duplicate of #198 and hope your cv is working again. If not just feel free to comment below.

**Closed** 2024-08-03 13:57 UTC
Labels: duplicate, not a bug
