### ISSUE TITLE
broken mailto when using IDN's

### ISSUE THREAD

**Issue by tuxmaster5000** [moderncv/moderncv#123] opened 2022-06-18 13:52 UTC
Sample:
`\email{foo@müller.foo}`
will render in the pdf correct, but the link is not punycode encoded(ACE).
The link it self is code as "foo@m�ller.foo" in stand of "foo@xn--mller-kva.foo"

**Comment by mefuller** [comment] 2022-06-18 14:19
This is really an issue with hyperref and not with moderncv

There is a workaround we could implement, but this requires breaking our current interface: https://tex.stackexchange.com/questions/375776/punycode-unicode-in-domain-names-is-not-converted-properly

@tuxmaster5000 you could certainly edit your own local copy to implement this change and open a PR if you find a reasonable way of doing it

I'm inclined to say that this is just not something that we are going to support independently of hyperref making an upstream change to add punycode

@stephanlachnit thoughts?

**Comment by mefuller** [comment] 2022-12-19 21:13
Closing this issue as "won't fix" since the problem is really hyperref (definitely above my paygrade)

**Closed by mefuller** 2022-12-19 21:13 UTC
Labels: wontfix
